/*
 * generated by Xtext 2.12.0
 */
package org.xtext.contextml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.contextml.ui.internal.ContextmlActivator;

public class ContextMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ContextmlActivator.getInstance().getInjector("org.xtext.contextml.ContextML");
	}

}
