/**
 * generated by Xtext 2.12.0
 */
package org.xtext.adaptui.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.adaptui.AdaptUIRuntimeModule;
import org.xtext.adaptui.AdaptUIStandaloneSetup;
import org.xtext.adaptui.ide.AdaptUIIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AdaptUIIdeSetup extends AdaptUIStandaloneSetup {
  @Override
  public Injector createInjector() {
    AdaptUIRuntimeModule _adaptUIRuntimeModule = new AdaptUIRuntimeModule();
    AdaptUIIdeModule _adaptUIIdeModule = new AdaptUIIdeModule();
    return Guice.createInjector(Modules2.mixin(_adaptUIRuntimeModule, _adaptUIIdeModule));
  }
}
