/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.adaptdsl.ide;

import org.xtext.example.adaptdsl.ide.AbstractAdaptDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AdaptDslIdeModule extends AbstractAdaptDslIdeModule {
}
