/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.adaptdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.adaptdsl.AdaptDslRuntimeModule;
import org.xtext.example.adaptdsl.AdaptDslStandaloneSetup;
import org.xtext.example.adaptdsl.ide.AdaptDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AdaptDslIdeSetup extends AdaptDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    AdaptDslRuntimeModule _adaptDslRuntimeModule = new AdaptDslRuntimeModule();
    AdaptDslIdeModule _adaptDslIdeModule = new AdaptDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_adaptDslRuntimeModule, _adaptDslIdeModule));
  }
}
