/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.adaptdsl.adaptDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add View Component Button Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getLangKey <em>Lang Key</em>}</li>
 *   <li>{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getAddViewComponentButtonOperation()
 * @model
 * @generated
 */
public interface AddViewComponentButtonOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getAddViewComponentButtonOperation_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Lang Key</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lang Key</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lang Key</em>' attribute.
   * @see #setLangKey(String)
   * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getAddViewComponentButtonOperation_LangKey()
   * @model
   * @generated
   */
  String getLangKey();

  /**
   * Sets the value of the '{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getLangKey <em>Lang Key</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lang Key</em>' attribute.
   * @see #getLangKey()
   * @generated
   */
  void setLangKey(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getAddViewComponentButtonOperation_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link org.xtext.example.adaptdsl.adaptDsl.AddViewComponentButtonOperation#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

} // AddViewComponentButtonOperation
