/**
 * generated by Xtext 2.11.0
 */
package org.xtext.example.adaptdsl.adaptDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.adaptdsl.adaptDsl.Model#getContextModel <em>Context Model</em>}</li>
 *   <li>{@link org.xtext.example.adaptdsl.adaptDsl.Model#getAdaptationModel <em>Adaptation Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Context Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Context Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Context Model</em>' containment reference.
   * @see #setContextModel(ContextModel)
   * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getModel_ContextModel()
   * @model containment="true"
   * @generated
   */
  ContextModel getContextModel();

  /**
   * Sets the value of the '{@link org.xtext.example.adaptdsl.adaptDsl.Model#getContextModel <em>Context Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Context Model</em>' containment reference.
   * @see #getContextModel()
   * @generated
   */
  void setContextModel(ContextModel value);

  /**
   * Returns the value of the '<em><b>Adaptation Model</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Adaptation Model</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adaptation Model</em>' containment reference.
   * @see #setAdaptationModel(AdaptationModel)
   * @see org.xtext.example.adaptdsl.adaptDsl.AdaptDslPackage#getModel_AdaptationModel()
   * @model containment="true"
   * @generated
   */
  AdaptationModel getAdaptationModel();

  /**
   * Sets the value of the '{@link org.xtext.example.adaptdsl.adaptDsl.Model#getAdaptationModel <em>Adaptation Model</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adaptation Model</em>' containment reference.
   * @see #getAdaptationModel()
   * @generated
   */
  void setAdaptationModel(AdaptationModel value);

} // Model
