/**
 * generated by Xtext 2.12.0
 */
package org.xtext.adaptui.adaptUI.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.xtext.adaptui.adaptUI.ActionCategory;
import org.xtext.adaptui.adaptUI.Actions;
import org.xtext.adaptui.adaptUI.AdaptCssClassOperation;
import org.xtext.adaptui.adaptUI.AdaptUIPackage;
import org.xtext.adaptui.adaptUI.AdaptationModel;
import org.xtext.adaptui.adaptUI.AdaptationRule;
import org.xtext.adaptui.adaptUI.AddNavLinkOperation;
import org.xtext.adaptui.adaptUI.AddViewComponentButtonOperation;
import org.xtext.adaptui.adaptUI.AddViewComponentOperation;
import org.xtext.adaptui.adaptUI.BoolValue;
import org.xtext.adaptui.adaptUI.BooleanCondition;
import org.xtext.adaptui.adaptUI.ChangeColorSchemeOperation;
import org.xtext.adaptui.adaptUI.ChangeFontOperation;
import org.xtext.adaptui.adaptUI.ChangeFontSizeOperation;
import org.xtext.adaptui.adaptUI.ChangeTableCssClassOperation;
import org.xtext.adaptui.adaptUI.ClearNavOperation;
import org.xtext.adaptui.adaptUI.ConditionalAndExpression;
import org.xtext.adaptui.adaptUI.ConditionalOrExpression;
import org.xtext.adaptui.adaptUI.ConditionalPrimary;
import org.xtext.adaptui.adaptUI.ContextModel;
import org.xtext.adaptui.adaptUI.DefType;
import org.xtext.adaptui.adaptUI.DefTypes;
import org.xtext.adaptui.adaptUI.DeleteNavLinkOperation;
import org.xtext.adaptui.adaptUI.DeleteViewComponentButtonOperation;
import org.xtext.adaptui.adaptUI.DeleteViewComponentOperation;
import org.xtext.adaptui.adaptUI.DisplayPropertyValue;
import org.xtext.adaptui.adaptUI.EditFactOperation;
import org.xtext.adaptui.adaptUI.Entity;
import org.xtext.adaptui.adaptUI.Enums;
import org.xtext.adaptui.adaptUI.Fact;
import org.xtext.adaptui.adaptUI.FactName;
import org.xtext.adaptui.adaptUI.FactProperty;
import org.xtext.adaptui.adaptUI.Function;
import org.xtext.adaptui.adaptUI.FunctionList;
import org.xtext.adaptui.adaptUI.IntValue;
import org.xtext.adaptui.adaptUI.Model;
import org.xtext.adaptui.adaptUI.NumberCondition;
import org.xtext.adaptui.adaptUI.ParentOperation;
import org.xtext.adaptui.adaptUI.Property;
import org.xtext.adaptui.adaptUI.Provider;
import org.xtext.adaptui.adaptUI.RedirectNavLinkOperation;
import org.xtext.adaptui.adaptUI.Service;
import org.xtext.adaptui.adaptUI.ServiceFunctionCallOperation;
import org.xtext.adaptui.adaptUI.ServiceList;
import org.xtext.adaptui.adaptUI.SetDisplayPropertyOperation;
import org.xtext.adaptui.adaptUI.StringCondition;
import org.xtext.adaptui.adaptUI.StringValue;
import org.xtext.adaptui.adaptUI.TYPE;
import org.xtext.adaptui.adaptUI.UpdateType;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.adaptui.adaptUI.AdaptUIPackage
 * @generated
 */
public class AdaptUIAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static AdaptUIPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AdaptUIAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = AdaptUIPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AdaptUISwitch<Adapter> modelSwitch =
    new AdaptUISwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseContextModel(ContextModel object)
      {
        return createContextModelAdapter();
      }
      @Override
      public Adapter caseAdaptationModel(AdaptationModel object)
      {
        return createAdaptationModelAdapter();
      }
      @Override
      public Adapter caseServiceList(ServiceList object)
      {
        return createServiceListAdapter();
      }
      @Override
      public Adapter caseService(Service object)
      {
        return createServiceAdapter();
      }
      @Override
      public Adapter caseFunctionList(FunctionList object)
      {
        return createFunctionListAdapter();
      }
      @Override
      public Adapter caseFunction(Function object)
      {
        return createFunctionAdapter();
      }
      @Override
      public Adapter caseAdaptationRule(AdaptationRule object)
      {
        return createAdaptationRuleAdapter();
      }
      @Override
      public Adapter caseConditionalOrExpression(ConditionalOrExpression object)
      {
        return createConditionalOrExpressionAdapter();
      }
      @Override
      public Adapter caseConditionalAndExpression(ConditionalAndExpression object)
      {
        return createConditionalAndExpressionAdapter();
      }
      @Override
      public Adapter caseConditionalPrimary(ConditionalPrimary object)
      {
        return createConditionalPrimaryAdapter();
      }
      @Override
      public Adapter caseBooleanCondition(BooleanCondition object)
      {
        return createBooleanConditionAdapter();
      }
      @Override
      public Adapter caseNumberCondition(NumberCondition object)
      {
        return createNumberConditionAdapter();
      }
      @Override
      public Adapter caseStringCondition(StringCondition object)
      {
        return createStringConditionAdapter();
      }
      @Override
      public Adapter caseFact(Fact object)
      {
        return createFactAdapter();
      }
      @Override
      public Adapter caseFactName(FactName object)
      {
        return createFactNameAdapter();
      }
      @Override
      public Adapter caseFactProperty(FactProperty object)
      {
        return createFactPropertyAdapter();
      }
      @Override
      public Adapter caseActions(Actions object)
      {
        return createActionsAdapter();
      }
      @Override
      public Adapter caseActionCategory(ActionCategory object)
      {
        return createActionCategoryAdapter();
      }
      @Override
      public Adapter caseParentOperation(ParentOperation object)
      {
        return createParentOperationAdapter();
      }
      @Override
      public Adapter caseServiceFunctionCallOperation(ServiceFunctionCallOperation object)
      {
        return createServiceFunctionCallOperationAdapter();
      }
      @Override
      public Adapter caseEditFactOperation(EditFactOperation object)
      {
        return createEditFactOperationAdapter();
      }
      @Override
      public Adapter caseSetDisplayPropertyOperation(SetDisplayPropertyOperation object)
      {
        return createSetDisplayPropertyOperationAdapter();
      }
      @Override
      public Adapter caseDisplayPropertyValue(DisplayPropertyValue object)
      {
        return createDisplayPropertyValueAdapter();
      }
      @Override
      public Adapter caseIntValue(IntValue object)
      {
        return createIntValueAdapter();
      }
      @Override
      public Adapter caseStringValue(StringValue object)
      {
        return createStringValueAdapter();
      }
      @Override
      public Adapter caseBoolValue(BoolValue object)
      {
        return createBoolValueAdapter();
      }
      @Override
      public Adapter caseAddViewComponentOperation(AddViewComponentOperation object)
      {
        return createAddViewComponentOperationAdapter();
      }
      @Override
      public Adapter caseDeleteViewComponentOperation(DeleteViewComponentOperation object)
      {
        return createDeleteViewComponentOperationAdapter();
      }
      @Override
      public Adapter caseAddViewComponentButtonOperation(AddViewComponentButtonOperation object)
      {
        return createAddViewComponentButtonOperationAdapter();
      }
      @Override
      public Adapter caseDeleteViewComponentButtonOperation(DeleteViewComponentButtonOperation object)
      {
        return createDeleteViewComponentButtonOperationAdapter();
      }
      @Override
      public Adapter caseAddNavLinkOperation(AddNavLinkOperation object)
      {
        return createAddNavLinkOperationAdapter();
      }
      @Override
      public Adapter caseDeleteNavLinkOperation(DeleteNavLinkOperation object)
      {
        return createDeleteNavLinkOperationAdapter();
      }
      @Override
      public Adapter caseRedirectNavLinkOperation(RedirectNavLinkOperation object)
      {
        return createRedirectNavLinkOperationAdapter();
      }
      @Override
      public Adapter caseClearNavOperation(ClearNavOperation object)
      {
        return createClearNavOperationAdapter();
      }
      @Override
      public Adapter caseChangeFontSizeOperation(ChangeFontSizeOperation object)
      {
        return createChangeFontSizeOperationAdapter();
      }
      @Override
      public Adapter caseChangeColorSchemeOperation(ChangeColorSchemeOperation object)
      {
        return createChangeColorSchemeOperationAdapter();
      }
      @Override
      public Adapter caseChangeFontOperation(ChangeFontOperation object)
      {
        return createChangeFontOperationAdapter();
      }
      @Override
      public Adapter caseChangeTableCssClassOperation(ChangeTableCssClassOperation object)
      {
        return createChangeTableCssClassOperationAdapter();
      }
      @Override
      public Adapter caseAdaptCssClassOperation(AdaptCssClassOperation object)
      {
        return createAdaptCssClassOperationAdapter();
      }
      @Override
      public Adapter caseEntity(Entity object)
      {
        return createEntityAdapter();
      }
      @Override
      public Adapter caseProperty(Property object)
      {
        return createPropertyAdapter();
      }
      @Override
      public Adapter caseProvider(Provider object)
      {
        return createProviderAdapter();
      }
      @Override
      public Adapter caseDefTypes(DefTypes object)
      {
        return createDefTypesAdapter();
      }
      @Override
      public Adapter caseDefType(DefType object)
      {
        return createDefTypeAdapter();
      }
      @Override
      public Adapter caseEnums(Enums object)
      {
        return createEnumsAdapter();
      }
      @Override
      public Adapter caseEnum(org.xtext.adaptui.adaptUI.Enum object)
      {
        return createEnumAdapter();
      }
      @Override
      public Adapter caseTYPE(TYPE object)
      {
        return createTYPEAdapter();
      }
      @Override
      public Adapter caseUpdateType(UpdateType object)
      {
        return createUpdateTypeAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ContextModel <em>Context Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ContextModel
   * @generated
   */
  public Adapter createContextModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AdaptationModel <em>Adaptation Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AdaptationModel
   * @generated
   */
  public Adapter createAdaptationModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ServiceList <em>Service List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ServiceList
   * @generated
   */
  public Adapter createServiceListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Service <em>Service</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Service
   * @generated
   */
  public Adapter createServiceAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.FunctionList <em>Function List</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.FunctionList
   * @generated
   */
  public Adapter createFunctionListAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Function
   * @generated
   */
  public Adapter createFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AdaptationRule <em>Adaptation Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AdaptationRule
   * @generated
   */
  public Adapter createAdaptationRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ConditionalOrExpression <em>Conditional Or Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ConditionalOrExpression
   * @generated
   */
  public Adapter createConditionalOrExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ConditionalAndExpression <em>Conditional And Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ConditionalAndExpression
   * @generated
   */
  public Adapter createConditionalAndExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ConditionalPrimary <em>Conditional Primary</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ConditionalPrimary
   * @generated
   */
  public Adapter createConditionalPrimaryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.BooleanCondition <em>Boolean Condition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.BooleanCondition
   * @generated
   */
  public Adapter createBooleanConditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.NumberCondition <em>Number Condition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.NumberCondition
   * @generated
   */
  public Adapter createNumberConditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.StringCondition <em>String Condition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.StringCondition
   * @generated
   */
  public Adapter createStringConditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Fact <em>Fact</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Fact
   * @generated
   */
  public Adapter createFactAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.FactName <em>Fact Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.FactName
   * @generated
   */
  public Adapter createFactNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.FactProperty <em>Fact Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.FactProperty
   * @generated
   */
  public Adapter createFactPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Actions
   * @generated
   */
  public Adapter createActionsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ActionCategory <em>Action Category</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ActionCategory
   * @generated
   */
  public Adapter createActionCategoryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ParentOperation <em>Parent Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ParentOperation
   * @generated
   */
  public Adapter createParentOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ServiceFunctionCallOperation <em>Service Function Call Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ServiceFunctionCallOperation
   * @generated
   */
  public Adapter createServiceFunctionCallOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.EditFactOperation <em>Edit Fact Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.EditFactOperation
   * @generated
   */
  public Adapter createEditFactOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.SetDisplayPropertyOperation <em>Set Display Property Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.SetDisplayPropertyOperation
   * @generated
   */
  public Adapter createSetDisplayPropertyOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DisplayPropertyValue <em>Display Property Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DisplayPropertyValue
   * @generated
   */
  public Adapter createDisplayPropertyValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.IntValue
   * @generated
   */
  public Adapter createIntValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.StringValue
   * @generated
   */
  public Adapter createStringValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.BoolValue <em>Bool Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.BoolValue
   * @generated
   */
  public Adapter createBoolValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AddViewComponentOperation <em>Add View Component Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AddViewComponentOperation
   * @generated
   */
  public Adapter createAddViewComponentOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DeleteViewComponentOperation <em>Delete View Component Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DeleteViewComponentOperation
   * @generated
   */
  public Adapter createDeleteViewComponentOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AddViewComponentButtonOperation <em>Add View Component Button Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AddViewComponentButtonOperation
   * @generated
   */
  public Adapter createAddViewComponentButtonOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DeleteViewComponentButtonOperation <em>Delete View Component Button Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DeleteViewComponentButtonOperation
   * @generated
   */
  public Adapter createDeleteViewComponentButtonOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AddNavLinkOperation <em>Add Nav Link Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AddNavLinkOperation
   * @generated
   */
  public Adapter createAddNavLinkOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DeleteNavLinkOperation <em>Delete Nav Link Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DeleteNavLinkOperation
   * @generated
   */
  public Adapter createDeleteNavLinkOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.RedirectNavLinkOperation <em>Redirect Nav Link Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.RedirectNavLinkOperation
   * @generated
   */
  public Adapter createRedirectNavLinkOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ClearNavOperation <em>Clear Nav Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ClearNavOperation
   * @generated
   */
  public Adapter createClearNavOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ChangeFontSizeOperation <em>Change Font Size Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ChangeFontSizeOperation
   * @generated
   */
  public Adapter createChangeFontSizeOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ChangeColorSchemeOperation <em>Change Color Scheme Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ChangeColorSchemeOperation
   * @generated
   */
  public Adapter createChangeColorSchemeOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ChangeFontOperation <em>Change Font Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ChangeFontOperation
   * @generated
   */
  public Adapter createChangeFontOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.ChangeTableCssClassOperation <em>Change Table Css Class Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.ChangeTableCssClassOperation
   * @generated
   */
  public Adapter createChangeTableCssClassOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.AdaptCssClassOperation <em>Adapt Css Class Operation</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.AdaptCssClassOperation
   * @generated
   */
  public Adapter createAdaptCssClassOperationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Entity
   * @generated
   */
  public Adapter createEntityAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Property <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Property
   * @generated
   */
  public Adapter createPropertyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Provider <em>Provider</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Provider
   * @generated
   */
  public Adapter createProviderAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DefTypes <em>Def Types</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DefTypes
   * @generated
   */
  public Adapter createDefTypesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.DefType <em>Def Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.DefType
   * @generated
   */
  public Adapter createDefTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Enums <em>Enums</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Enums
   * @generated
   */
  public Adapter createEnumsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.Enum <em>Enum</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.Enum
   * @generated
   */
  public Adapter createEnumAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.TYPE <em>TYPE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.TYPE
   * @generated
   */
  public Adapter createTYPEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.adaptui.adaptUI.UpdateType <em>Update Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.adaptui.adaptUI.UpdateType
   * @generated
   */
  public Adapter createUpdateTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //AdaptUIAdapterFactory
