/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.adaptdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.adaptdsl.ui.internal.AdaptdslActivator;

public class AdaptDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AdaptdslActivator.getInstance().getInjector("org.xtext.example.adaptdsl.AdaptDsl");
	}

}
