/*
 * generated by Xtext 2.12.0
 */
package org.xtext.adaptui.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.adaptui.ui.internal.AdaptuiActivator;

public class AdaptUIUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AdaptuiActivator.getInstance().getInjector("org.xtext.adaptui.AdaptUI");
	}

}
