/**
 * generated by Xtext 2.12.0
 */
package org.xtext.contextml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.contextml.ContextMLRuntimeModule;
import org.xtext.contextml.ContextMLStandaloneSetup;
import org.xtext.contextml.ide.ContextMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ContextMLIdeSetup extends ContextMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    ContextMLRuntimeModule _contextMLRuntimeModule = new ContextMLRuntimeModule();
    ContextMLIdeModule _contextMLIdeModule = new ContextMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_contextMLRuntimeModule, _contextMLIdeModule));
  }
}
